name: Build and Release Action
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: "v(.*)"
      - name: Build
        run: npm run build
        env:
          VERSION: ${{ steps.tagName.outputs.tag }}
          DEFAULT_SERVER_URL: wss://ws-gsm.vanflux.dev
      - name: Prepare mod artifact
        run: mv build/prod/chrome/raw/page.js gsm-mod.js
      - name: Build RELEASE_final.md
        run: envsubst < RELEASE.md > RELEASE_final.md
        env:
          VERSION: ${{ steps.tagName.outputs.tag }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gsm-bookmark.html,gsm-mod.js"
          name: Release ${{ steps.tagName.outputs.tag }}
          bodyFile: RELEASE_final.md
          token: ${{ secrets.GITHUB_TOKEN }}
