name: Build and Release Action
on:
  push:
    branches:
      - 'release/**'
      - 'rc/**'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Get version number
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF_NAME##*/}
      - name: Build
        run: npm run build
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          DEFAULT_SERVER_URL: wss://ws-gsm.vanflux.dev
      - name: Prepare mod artifact
        run: mv build/prod/chrome/raw/page.js gsm-mod.js
      - name: Build RELEASE_final.md
        run: envsubst < RELEASE.md > RELEASE_final.md
        env:
          VERSION: ${{ steps.vars.outputs.version }}
      - name: Create Release
        if: contains(github.ref, "release")
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gsm-bookmark.html,gsm-mod.js"
          tag: v${{ steps.vars.outputs.version }}
          name: Release ${{ steps.vars.outputs.version }}
          bodyFile: RELEASE_final.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release Candidate
        if: contains(github.ref, "rc")
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          artifacts: "gsm-bookmark.html,gsm-mod.js"
          tag: v${{ steps.vars.outputs.version }}
          name: Release Candidate ${{ steps.vars.outputs.version }}
          bodyFile: RELEASE_final.md
          token: ${{ secrets.GITHUB_TOKEN }}
